//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IX.Sandbox.Memory
{
    using global::System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IX.Sandbox.Memory.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The sub-scope is different from what has already been stored in this scope..
        /// </summary>
        internal static string SubScopeDifferentThanStored
        {
            get
            {
                return ResourceManager.GetString("SubScopeDifferentThanStored", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The sub-scope was not found..
        /// </summary>
        internal static string SubScopeNotFound
        {
            get
            {
                return ResourceManager.GetString("SubScopeNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The contained value type is not supported..
        /// </summary>
        internal static string TheContainedValueTypeIsNotSupported
        {
            get
            {
                return ResourceManager.GetString("TheContainedValueTypeIsNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The object has already been marked for collection..
        /// </summary>
        internal static string TheObjectHasAlreadyBeenMarkedForCollection
        {
            get
            {
                return ResourceManager.GetString("TheObjectHasAlreadyBeenMarkedForCollection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The sandbox heap has already been disposed..
        /// </summary>
        internal static string TheSandboxHeapHasAlreadyBeenDisposed
        {
            get
            {
                return ResourceManager.GetString("TheSandboxHeapHasAlreadyBeenDisposed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The supplied object key is invalid..
        /// </summary>
        internal static string TheSuppliedObjectKeyIsInvalid
        {
            get
            {
                return ResourceManager.GetString("TheSuppliedObjectKeyIsInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The symbol was already created..
        /// </summary>
        internal static string TheSymbolWasAlreadyCreated
        {
            get
            {
                return ResourceManager.GetString("TheSymbolWasAlreadyCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The value type is not suppported, since an attempt was made to assign an array of values to a single value symbol..
        /// </summary>
        internal static string TheValueTypeIsNotSuppportedSinceAnAttemptWasMadeToAssignAnArrayOfValuesToASingleValueSymbol
        {
            get
            {
                return ResourceManager.GetString("TheValueTypeIsNotSuppportedSinceAnAttemptWasMadeToAssignAnArrayOfValuesToASingleV" +
                        "alueSymbol", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The variable is different from what has already been stored in this scope..
        /// </summary>
        internal static string VariableDifferentThanStored
        {
            get
            {
                return ResourceManager.GetString("VariableDifferentThanStored", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The variable was not found..
        /// </summary>
        internal static string VariableNotFound
        {
            get
            {
                return ResourceManager.GetString("VariableNotFound", resourceCulture);
            }
        }
    }
}
