version: 0.5.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
clone_depth: 1
environment:
  NUGET_SECURE_TOKEN:
    secure: h6maB3fFIf8BLMo7XceNcgu8h6OL79XzgS+2YxMZY8Qvkni0iJo5A6im7AILprC1
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: >-
    msbuild src\IX.Framework.sln /p:Configuration=Release /t:Clean

    msbuild src\IX.Framework.sln /p:Configuration=Debug /t:Clean

    cd src\IX.StandardExtensions\

    dotnet csprojVersioning IX.StandardExtensions.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.StandardExtensions.ComponentModel\

    dotnet csprojVersioning IX.StandardExtensions.ComponentModel.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.StandardExtensions.TestUtils\

    dotnet csprojVersioning IX.StandardExtensions.TestUtils.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.StandardExtensions.Threading\

    dotnet csprojVersioning IX.StandardExtensions.Threading.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Abstractions\

    dotnet csprojVersioning IX.Abstractions.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Abstractions.Collections\

    dotnet csprojVersioning IX.Abstractions.Collections.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Abstractions.FileSystem\

    dotnet csprojVersioning IX.Abstractions.FileSystem.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Abstractions.Moq\

    dotnet csprojVersioning IX.Abstractions.Moq.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Abstractions.Threading\

    dotnet csprojVersioning IX.Abstractions.Threading.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Undoable\

    dotnet csprojVersioning IX.Undoable.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Undoable.WPF\

    dotnet csprojVersioning IX.Undoable.WPF.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Observable\

    dotnet csprojVersioning IX.Observable.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Sandbox.Memory\

    dotnet csprojVersioning IX.Sandbox.Memory.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Retry\

    dotnet csprojVersioning IX.Retry.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Math\

    dotnet csprojVersioning IX.Math.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.StandardExtensions.WPF\

    dotnet csprojVersioning IX.StandardExtensions.WPF.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\..\
build:
  project: src\IX.Framework.sln
  parallel: true
  verbosity: minimal
test:
  categories:
    except:
    - BenchmarkTests
deploy_script:
- cmd: >-
    if "%NUGET_SECURE_TOKEN%" neq "" nuget push src\IX.StandardExtensions\bin\Release\IX.StandardExtensions.%APPVEYOR_BUILD_VERSION%.nupkg -ApiKey %NUGET_SECURE_TOKEN% -Source https://ci.appveyor.com/nuget/adimosh-at-live-dot-com/api/v2/package

    if "%NUGET_SECURE_TOKEN%" neq "" nuget push src\IX.StandardExtensions.ComponentModel\bin\Release\IX.StandardExtensions.ComponentModel.%APPVEYOR_BUILD_VERSION%.nupkg -ApiKey %NUGET_SECURE_TOKEN% -Source https://ci.appveyor.com/nuget/adimosh-at-live-dot-com/api/v2/package

    if "%NUGET_SECURE_TOKEN%" neq "" nuget push src\IX.StandardExtensions.TestUtils\bin\Release\IX.StandardExtensions.TestUtils.%APPVEYOR_BUILD_VERSION%.nupkg -ApiKey %NUGET_SECURE_TOKEN% -Source https://ci.appveyor.com/nuget/adimosh-at-live-dot-com/api/v2/package

    if "%NUGET_SECURE_TOKEN%" neq "" nuget push src\IX.StandardExtensions.Threading\bin\Release\IX.StandardExtensions.Threading.%APPVEYOR_BUILD_VERSION%.nupkg -ApiKey %NUGET_SECURE_TOKEN% -Source https://ci.appveyor.com/nuget/adimosh-at-live-dot-com/api/v2/package

    if "%NUGET_SECURE_TOKEN%" neq "" nuget push src\IX.Abstractions\bin\Release\IX.Abstractions.%APPVEYOR_BUILD_VERSION%.nupkg -ApiKey %NUGET_SECURE_TOKEN% -Source https://ci.appveyor.com/nuget/adimosh-at-live-dot-com/api/v2/package

    if "%NUGET_SECURE_TOKEN%" neq "" nuget push src\IX.Abstractions.Collections\bin\Release\IX.Abstractions.Collections.%APPVEYOR_BUILD_VERSION%.nupkg -ApiKey %NUGET_SECURE_TOKEN% -Source https://ci.appveyor.com/nuget/adimosh-at-live-dot-com/api/v2/package

    if "%NUGET_SECURE_TOKEN%" neq "" nuget push src\IX.Abstractions.FileSystem\bin\Release\IX.Abstractions.FileSystem.%APPVEYOR_BUILD_VERSION%.nupkg -ApiKey %NUGET_SECURE_TOKEN% -Source https://ci.appveyor.com/nuget/adimosh-at-live-dot-com/api/v2/package

    if "%NUGET_SECURE_TOKEN%" neq "" nuget push src\IX.Abstractions.Moq\bin\Release\IX.Abstractions.Moq.%APPVEYOR_BUILD_VERSION%.nupkg -ApiKey %NUGET_SECURE_TOKEN% -Source https://ci.appveyor.com/nuget/adimosh-at-live-dot-com/api/v2/package

    if "%NUGET_SECURE_TOKEN%" neq "" nuget push src\IX.Abstractions.Threading\bin\Release\IX.Abstractions.Threading.%APPVEYOR_BUILD_VERSION%.nupkg -ApiKey %NUGET_SECURE_TOKEN% -Source https://ci.appveyor.com/nuget/adimosh-at-live-dot-com/api/v2/package

    if "%NUGET_SECURE_TOKEN%" neq "" nuget push src\IX.Undoable\bin\Release\IX.Undoable.%APPVEYOR_BUILD_VERSION%.nupkg -ApiKey %NUGET_SECURE_TOKEN% -Source https://ci.appveyor.com/nuget/adimosh-at-live-dot-com/api/v2/package

    if "%NUGET_SECURE_TOKEN%" neq "" nuget push src\IX.Undoable.WPF\bin\Release\IX.Undoable.WPF.%APPVEYOR_BUILD_VERSION%.nupkg -ApiKey %NUGET_SECURE_TOKEN% -Source https://ci.appveyor.com/nuget/adimosh-at-live-dot-com/api/v2/package

    if "%NUGET_SECURE_TOKEN%" neq "" nuget push src\IX.Observable\bin\Release\IX.Observable.%APPVEYOR_BUILD_VERSION%.nupkg -ApiKey %NUGET_SECURE_TOKEN% -Source https://ci.appveyor.com/nuget/adimosh-at-live-dot-com/api/v2/package

    if "%NUGET_SECURE_TOKEN%" neq "" nuget push src\IX.Sandbox.Memory\bin\Release\IX.Sandbox.Memory.%APPVEYOR_BUILD_VERSION%.nupkg -ApiKey %NUGET_SECURE_TOKEN% -Source https://ci.appveyor.com/nuget/adimosh-at-live-dot-com/api/v2/package

    if "%NUGET_SECURE_TOKEN%" neq "" nuget push src\IX.Retry\bin\Release\IX.Retry.%APPVEYOR_BUILD_VERSION%.nupkg -ApiKey %NUGET_SECURE_TOKEN% -Source https://ci.appveyor.com/nuget/adimosh-at-live-dot-com/api/v2/package

    if "%NUGET_SECURE_TOKEN%" neq "" nuget push src\IX.Math\bin\Release\IX.Math.%APPVEYOR_BUILD_VERSION%.nupkg -ApiKey %NUGET_SECURE_TOKEN% -Source https://ci.appveyor.com/nuget/adimosh-at-live-dot-com/api/v2/package
    
    if "%NUGET_SECURE_TOKEN%" neq "" nuget push src\IX.StandardExtensions.WPF\bin\Release\IX.StandardExtensions.WPF.%APPVEYOR_BUILD_VERSION%.nupkg -ApiKey %NUGET_SECURE_TOKEN% -Source https://ci.appveyor.com/nuget/adimosh-at-live-dot-com/api/v2/package