version: 0.5.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
clone_depth: 1
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: >-

    dotnet clean src\IX.Framework.sln -c Release

    dotnet clean src\IX.Framework.sln -c Debug

    dotnet restore src/IX.Framework.sln


    cd src\IX.StandardExtensions\

    dotnet csprojVersioning IX.StandardExtensions.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.StandardExtensions.ComponentModel\

    dotnet csprojVersioning IX.StandardExtensions.ComponentModel.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.StandardExtensions.TestUtils\

    dotnet csprojVersioning IX.StandardExtensions.TestUtils.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.StandardExtensions.Threading\

    dotnet csprojVersioning IX.StandardExtensions.Threading.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Abstractions\

    dotnet csprojVersioning IX.Abstractions.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Abstractions.Collections\

    dotnet csprojVersioning IX.Abstractions.Collections.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Abstractions.FileSystem\

    dotnet csprojVersioning IX.Abstractions.FileSystem.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Abstractions.Moq\

    dotnet csprojVersioning IX.Abstractions.Moq.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Abstractions.Threading\

    dotnet csprojVersioning IX.Abstractions.Threading.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Undoable\

    dotnet csprojVersioning IX.Undoable.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Undoable.WPF\

    dotnet csprojVersioning IX.Undoable.WPF.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Observable\

    dotnet csprojVersioning IX.Observable.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Sandbox.Memory\

    dotnet csprojVersioning IX.Sandbox.Memory.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Retry\

    dotnet csprojVersioning IX.Retry.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Math\

    dotnet csprojVersioning IX.Math.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.StandardExtensions.WPF\

    dotnet csprojVersioning IX.StandardExtensions.WPF.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\IX.Guaranteed\

    dotnet csprojVersioning IX.Guaranteed.csproj %APPVEYOR_BUILD_VERSION%

    cd ..\..\

    dotnet clean src\IX.Framework.sln -c Release

    dotnet clean src\IX.Framework.sln -c Debug

    dotnet restore src/IX.Framework.sln
build:
  project: src\IX.Framework.sln
  parallel: true
  verbosity: minimal
test:
  categories:
    except:
    - BenchmarkTests
artifacts:
- path: src\IX.StandardExtensions\bin\Release\IX.StandardExtensions.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.StandardExtensions
- path: src\IX.StandardExtensions.ComponentModel\bin\Release\IX.StandardExtensions.ComponentModel.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.StandardExtensions.ComponentModel
- path: src\IX.StandardExtensions.TestUtils\bin\Release\IX.StandardExtensions.TestUtils.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.StandardExtensions.TestUtils
- path: src\IX.StandardExtensions.Threading\bin\Release\IX.StandardExtensions.Threading.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.StandardExtensions.Threading
- path: src\IX.Abstractions\bin\Release\IX.Abstractions.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.Abstractions
- path: src\IX.Abstractions.Collections\bin\Release\IX.Abstractions.Collections.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.Abstractions.Collections
- path: src\IX.Abstractions.FileSystem\bin\Release\IX.Abstractions.FileSystem.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.Abstractions.FileSystem
- path: src\IX.Abstractions.Moq\bin\Release\IX.Abstractions.Moq.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.Abstractions.Moq
- path: src\IX.Abstractions.Threading\bin\Release\IX.Abstractions.Threading.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.Abstractions.Threading
- path: src\IX.Undoable\bin\Release\IX.Undoable.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.Undoable
- path: src\IX.Undoable.WPF\bin\Release\IX.Undoable.WPF.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.Undoable.WPF
- path: src\IX.Observable\bin\Release\IX.Observable.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.Observable
- path: src\IX.Sandbox.Memory\bin\Release\IX.Sandbox.Memory.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.Sandbox.Memory
- path: src\IX.Retry\bin\Release\IX.Retry.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.Retry
- path: src\IX.Math\bin\Release\IX.Math.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.Math
- path: src\IX.StandardExtensions.WPF\bin\Release\IX.StandardExtensions.WPF.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.StandardExtensions.WPF
- path: src\IX.Guaranteed\bin\Release\IX.Guaranteed.%APPVEYOR_BUILD_VERSION%.nupkg
  name: IX.Guaranteed
deploy:
- provider: NuGet
  server: https://ci.appveyor.com/nuget/adimosh-at-live-dot-com/api/v2/package
  api_key:
    secure: eF0Mu+Ky+FtngFJN7u4unv9l2ebEvlvfim9hPpWkRAc=
  skip_symbols: true