trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - doc/*
    - src/*.yaml
    - README.md
    - LICENSE.md
    - .gitignore
    - src/.editorconfig

pr:
  autoCancel: true
  branches:
    include:
    - master
  paths:
    exclude:
    - doc/*
    - src/*.yaml
    - README.md
    - LICENSE.md
    - .gitignore
    - src/.editorconfig

variables:
  IxDevOpsBuild: true
  IxVersionPrefix: 0.6.0
  IxVersionSuffix:
  disable.coverage.autogenerate: true
  system.debug: false

# Jobs should run in parallel

resources:
  repositories:
    - repository: templates
      type: github
      name: adimosh/IX.Framework.Operations
      endpoint: adimosh

jobs:
- job:
  workspace:
    clean: all
  timeoutInMinutes: 10
  pool:
    name: Azure Pipelines
    vmImage: windows-latest
  steps:
  - template: yaml/job-master-build.yml@templates
    parameters:
      solutionName: 'IX.Framework'
- job:
  workspace:
    clean: all
  timeoutInMinutes: 10
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest
  steps:
  - template: yaml/job-master-build.yml@templates
    parameters:
      solutionName: 'IX.Framework'
- job:
  workspace:
    clean: all
  timeoutInMinutes: 10
  pool:
    name: Azure Pipelines
    vmImage: macOS-latest
  steps:
  - template: yaml/job-master-build.yml@templates
    parameters:
      solutionName: 'IX.Framework'