trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - doc/*
    - src/*.yaml
    - README.md
    - LICENSE.md
    - .gitignore
    - src/.editorconfig

pr:
  autoCancel: true
  branches:
    include:
    - master
  paths:
    exclude:
    - doc/*
    - src/*.yaml
    - README.md
    - LICENSE.md
    - .gitignore
    - src/.editorconfig

variables:
  IxDevOpsBuild: true
  IxVersionPrefix: 0.5.0
  IxVersionSuffix:
  system.debug: false

# Jobs should run in parallel

jobs:
- job:
  timeoutInMinutes: 10
  pool:
    name: Azure Pipelines
    vmImage: windows-latest
  steps:
  - template: ../opt/job-master-build.yml
    parameters:
      solutionName: 'IX.Framework'
- job:
  timeoutInMinutes: 10
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest
  steps:
  - template: ../opt/job-master-build.yml
    parameters:
      solutionName: 'IX.Framework'
- job:
  timeoutInMinutes: 10
  pool:
    name: Azure Pipelines
    vmImage: macOS-latest
  steps:
  - template: ../opt/job-master-build.yml
    parameters:
      solutionName: 'IX.Framework'