pool:
  name: Hosted Windows 2019 with VS2019
  demands: vstest

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - doc/*
    - src/*.yaml
    - README.md
    - LICENSE.md
    - .gitignore
    - src/.editorconfig
    - IXLogo.png
    - src/QuickDirtyTests/*

pr:
  autoCancel: true
  branches:
    include:
    - master
  paths:
    exclude:
    - doc/*
    - src/*.yaml
    - README.md
    - LICENSE.md
    - .gitignore
    - src/.editorconfig
    - IXLogo.png
    - src/QuickDirtyTests/*

variables:
  IxDevOpsBuild: true
  IxVersionPrefix: 0.5.0
  IxVersionSuffix:
  system.debug: false

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore interdependencies (project system)'
  inputs:
    command: restore
    projects: src/IX.Framework.sln
    verbosityRestore: Minimal

- task: DotNetCoreCLI@2
  displayName: 'Restore interdependencies (actual dependencies)'
  inputs:
    command: restore
    projects: 'src/**/*.csproj'
    arguments: '--force --verbosity minimal'

- task: DotNetCoreCLI@2
  displayName: 'Build in debug'
  inputs:
    projects: src/IX.Framework.sln
    arguments: '-c Debug --version-suffix alpha'

- task: VSTest@2
  displayName: 'Unit tests for debug'
  inputs:
    codeCoverageEnabled: true
    diagnosticsEnabled: True

- task: DotNetCoreCLI@2
  displayName: 'Clean up'
  inputs:
    command: custom
    projects: src/IX.Framework.sln
    custom: clean

- task: DotNetCoreCLI@2
  displayName: 'Build in release'
  inputs:
    projects: src/IX.Framework.sln
    arguments: '-c Release --version-suffix alpha'

- task: VSTest@2
  displayName: 'Unit tests for release'