pool:
  name: Hosted Windows 2019 with VS2019
  demands: vstest

trigger:
  branches:
    include:
    - dev
  paths:
    exclude:
    - doc/*
    - src/*.yaml
    - README.md
    - LICENSE.md
    - .gitignore
    - src/.editorconfig
    - IXLogo.png

pr:
  autoCancel: true
  branches:
    include:
    - dev
  paths:
    exclude:
    - doc/*
    - src/*.yaml
    - README.md
    - LICENSE.md
    - .gitignore
    - src/.editorconfig
    - IXLogo.png

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore interdependencies'
  inputs:
    command: restore
    projects: src/IX.Framework.sln
    verbosityRestore: Minimal

- task: DotNetCoreCLI@2
  displayName: 'Build in debug'
  inputs:
    projects: src/IX.Framework.sln
    arguments: '-c Debug --version-suffix alpha'

- task: VSTest@2
  displayName: 'Unit tests for debug'
  inputs:
    codeCoverageEnabled: true
    diagnosticsEnabled: True
