pool:
  name: Hosted Windows 2019 with VS2019
  vmImage: windows-latest

trigger: none

pr: none

variables:
  IxDevOpsBuild: true
  disable.coverage.autogenerate: true
  system.debug: false

resources:
  repositories:
    - repository: templates
      type: github
      name: adimosh/IX.Framework.Operations
      endpoint: adimosh

jobs:
- job:
  timeoutInMinutes: 10
  pool:
    name: Azure Pipelines
    vmImage: windows-latest
  steps:
  - template: yaml/job-release-build.yml@templates
    parameters:
      solutionName: 'IX.Framework'